# Generated by Django 3.2 on 2021-12-12 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0002_historicalrule_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='apply_to_customers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
