# Generated by Django 3.2 on 2021-12-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_rule_apply_to_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='apply_to_products',
        ),
    ]
