# Generated by Django 3.2 on 2021-12-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_remove_discount_apply_to_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='activate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='deactivate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiscount',
            name='activate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiscount',
            name='deactivate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
