# Generated by Django 3.2 on 2021-12-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_auto_20211213_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiscount',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiscount',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
