# Generated by Django 3.2 on 2021-12-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_auto_20211213_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrule',
            name='type',
            field=models.CharField(choices=[('Minimum Price', 'Minimum Price'), ('Product', 'Product'), ('Number of Orders', 'Number of Orders'), ('Customer Set', 'Customer Set'), ('Nth-time Subscribers', 'Nth-time Subscribers')], max_length=128),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('Minimum Price', 'Minimum Price'), ('Product', 'Product'), ('Number of Orders', 'Number of Orders'), ('Customer Set', 'Customer Set'), ('Nth-time Subscribers', 'Nth-time Subscribers')], max_length=128),
        ),
    ]
