# Generated by Django 3.2 on 2021-12-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_auto_20211215_0507'),
        ('discounts', '0007_auto_20211216_1952'),
    ]

    operations = [
    ]
