# Generated by Django 3.2 on 2022-01-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_merge_0007_auto_20211215_0507_0007_auto_20211216_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscount',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomerdiscount',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
