# Generated by Django 3.2 on 2022-02-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20220210_1834'),
        ('discounts', '0009_auto_20220127_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdiscount',
            name='customer_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_discounts', to='customers.customerchild'),
        ),
    ]
