# Generated by Django 3.2 on 2022-02-22 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_alter_customerdiscount_customer_child'),
    ]

    operations = [
    ]
