# Generated by Django 3.2 on 2022-02-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_auto_20220222_0208'),
        ('discounts', '0013_merge_20220222_2334'),
    ]

    operations = [
    ]
