# Generated by Django 3.2 on 2022-03-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0018_alter_discount_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='from_yotpo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldiscount',
            name='from_yotpo',
            field=models.BooleanField(default=False),
        ),
    ]
