# Generated by Django 3.2 on 2022-04-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0019_auto_20220321_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='from_brightback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldiscount',
            name='from_brightback',
            field=models.BooleanField(default=False),
        ),
    ]
