apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/eksctl
patchesJson6902:
  - target:
      version: v1alpha5
      kind: ClusterConfig
      group: eksctl.io
      name: cluster-name
    path: cluster.patch.yaml
