apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-tmp
  namespace: staging-1
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
