apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-tmp
  # No namespace, PVs are global
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  - noresvport
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /
    server: fs-010c4208e84ed207e.efs.us-east-1.amazonaws.com
  claimRef:
    name: backend-tmp
    namespace: staging-1
