# Generated by Django 3.2 on 2021-12-12 04:30

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('modified_at', models.DateTimeField(auto_created=True, auto_now=True, db_index=True, verbose_name='last modified at')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CartLineItem',
            fields=[
                ('modified_at', models.DateTimeField(auto_created=True, auto_now=True, db_index=True, verbose_name='last modified at')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCart',
            fields=[
                ('modified_at', models.DateTimeField(auto_created=True, blank=True, db_index=True, editable=False, verbose_name='last modified at')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, db_index=True, editable=False)),
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cart',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCartLineItem',
            fields=[
                ('modified_at', models.DateTimeField(auto_created=True, blank=True, db_index=True, editable=False, verbose_name='last modified at')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, db_index=True, editable=False)),
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cart', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carts.cart')),
            ],
            options={
                'verbose_name': 'historical cart line item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
