# Generated by Django 3.2 on 2022-06-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_auto_20220607_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulfillmentcenter',
            old_name='zipcode',
            new_name='zipcodes',
        ),
    ]
