# Generated by Django 3.2 on 2022-01-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211213_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshippingrate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
