# Generated by Django 3.2 on 2022-01-30 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20220129_0706'),
        ('orders', '0005_auto_20220125_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associated_orders', to='billing.paymentmethod'),
        ),
    ]
