# Generated by Django 3.2 on 2022-02-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220130_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='charge_failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='charge_failure_message',
            field=models.TextField(blank=True),
        ),
    ]
