# Generated by Django 3.2 on 2022-03-01 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220215_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='discount_amount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
