# Generated by Django 3.2 on 2022-03-08 14:39

import apps.orders.libs
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_backfill_subtotal_and_discount_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='synced_to_shopify_status',
            field=django_fsm.FSMField(choices=[('synced', 'synced'), ('pending', 'pending')], default=apps.orders.libs.OrderSyncedToShopifyStatusEnum['pending'], max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='synced_to_shopify_status',
            field=django_fsm.FSMField(choices=[('synced', 'synced'), ('pending', 'pending')], default=apps.orders.libs.OrderSyncedToShopifyStatusEnum['pending'], max_length=50),
        ),
    ]
