# Generated by Django 3.2 on 2022-03-08 14:39

from django.db import migrations


_update_synced_to_shopify_orders = '''
    update orders_order
       set synced_to_shopify_status = 'synced'
     where synced_to_shopify = true
'''


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20220308_1439'),
    ]

    operations = [
        migrations.RunSQL(_update_synced_to_shopify_orders)
    ]
