# Generated by Django 3.2 on 2022-03-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20220130_0022'),
        ('orders', '0013_update_synced_to_shopify_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='addresses.location'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.location'),
        ),
    ]
