# Generated by Django 3.2 on 2022-03-08 16:33

from django.db import migrations

_backfill_shipping_addresses = """
    update orders_order _ord
       set shipping_address_id = _al.id
      from (
        select al.id,
               al.customer_id
          from orders_order o
          join addresses_location al
            on al.customer_id = o.customer_id
        ) _al
    where _ord.shipping_address_id is null 
      and _al.customer_id = _ord.customer_id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220308_1557'),
    ]

    operations = [
        migrations.RunSQL(_backfill_shipping_addresses)
    ]
