# Generated by Django 3.2 on 2022-03-08 17:01

import apps.orders.libs
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_backfill_shipping_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='order_confirmation_email_status',
            field=django_fsm.FSMField(choices=[('sent', 'sent'), ('unsent', 'unsent')], default=apps.orders.libs.OrderConfirmationEmailStatus['unsent'], max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_confirmation_email_status',
            field=django_fsm.FSMField(choices=[('sent', 'sent'), ('unsent', 'unsent')], default=apps.orders.libs.OrderConfirmationEmailStatus['unsent'], max_length=50),
        ),
    ]
