# Generated by Django 3.2 on 2022-03-08 17:03

from django.db import migrations


_set_order_confirmation_email_sent_status_sql = """
    update orders_order
       set order_confirmation_email_status = 'sent'
     where synced_to_shopify = true
"""


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20220308_1701'),
    ]

    operations = [
        migrations.RunSQL(_set_order_confirmation_email_sent_status_sql),
    ]
