# Generated by Django 3.2 on 2022-03-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_set_order_confirmation_email_sent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='refund_reason',
            field=models.TextField(choices=[('', ''), ('Order Cancellation', 'Order Cancellation'), ('Order Issue', 'Order Issue')], default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.TextField(choices=[('', ''), ('Order Cancellation', 'Order Cancellation'), ('Order Issue', 'Order Issue')], default=''),
        ),
    ]
