# Generated by Django 3.2 on 2022-03-31 16:27
from django.apps import apps
from django.db import migrations


def add_default_cancellation_reason_for_orders(*args):
    Order = apps.get_model('orders', 'Order')

    # for order in Order.objects.filter():
    #     order.refund_reason = ''
    #     order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20220329_1759'),
    ]

    operations = [
        migrations.RunPython(add_default_cancellation_reason_for_orders),
    ]
