# Generated by Django 3.2 on 2022-04-13 18:28

from django.db import migrations

update_order_tax_client_sync_status = """
    update orders_order
       set synced_to_avalara = true
     where synced_to_shopify = true
       and payment_status = 'paid'; 
"""


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20220413_1822'),
    ]

    operations = [
        migrations.RunSQL(update_order_tax_client_sync_status),
    ]
