# Generated by Django 3.2 on 2022-01-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='setup_for_future_charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='setup_for_future_charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalpaymentmethod',
            name='last_four',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='last_four',
            field=models.TextField(),
        ),
    ]
