apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-tmp
  namespace: production
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
