# Generated by Django 3.2 on 2021-12-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_historicalwebhookevent_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebhookevent',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
