# Generated by Django 3.2 on 2022-01-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20220122_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
