# Generated by Django 3.2 on 2022-06-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20220130_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.TextField(blank=True),
        ),
    ]
