# Generated by Django 3.2 on 2022-01-04 21:12

import apps.customers.models.validators.customer_subscription
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20211220_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='next_order_changes_enabled_date',
            field=models.DateField(blank=True, null=True, validators=[apps.customers.models.validators.customer_subscription.validate_charge_date]),
        ),
        migrations.AlterField(
            model_name='historicalcustomersubscription',
            name='next_order_changes_enabled_date',
            field=models.DateField(blank=True, null=True, validators=[apps.customers.models.validators.customer_subscription.validate_charge_date]),
        ),
    ]
