# Generated by Django 3.2 on 2022-01-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20220129_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='recharge_customer_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='recharge_customer_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
