# Generated by Django 3.2 on 2022-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20220131_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerchild',
            name='sex',
            field=models.TextField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('their', 'their'), ('none', 'none')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomerchild',
            name='sex',
            field=models.TextField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('their', 'their'), ('none', 'none')], null=True),
        ),
    ]
