# Generated by Django 3.2 on 2022-02-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20220203_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerchild',
            name='allergy_severity',
            field=models.TextField(choices=[('none', 'none'), ('allergic', 'allergic')], default='none'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerchild',
            name='allergy_severity',
            field=models.TextField(choices=[('none', 'none'), ('allergic', 'allergic')], default='none'),
        ),
    ]
