# Generated by Django 3.2 on 2022-04-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20220210_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='synced_to_klaviyo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomersubscription',
            name='synced_to_klaviyo',
            field=models.BooleanField(default=False),
        ),
    ]
