# Generated by Django 3.2 on 2022-05-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20220427_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='updated_profile_fields_to_klaviyo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomersubscription',
            name='updated_profile_fields_to_klaviyo',
            field=models.BooleanField(default=False),
        ),
    ]
