# Generated by Django 3.2 on 2022-06-08 06:28

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20220512_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='status',
            field=django_fsm.FSMField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pause', 'pause')], default='inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcustomersubscription',
            name='status',
            field=django_fsm.FSMField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pause', 'pause')], default='inactive', max_length=50),
        ),
    ]
