# Generated by Django 3.2 on 2022-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20220608_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomersubscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
