# Generated by Django 3.2 on 2022-07-01 16:14

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20220608_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='status',
            field=django_fsm.FSMField(choices=[('active', 'active'), ('inactive', 'inactive'), ('paused', 'paused')], default='inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcustomersubscription',
            name='status',
            field=django_fsm.FSMField(choices=[('active', 'active'), ('inactive', 'inactive'), ('paused', 'paused')], default='inactive', max_length=50),
        ),
    ]
