apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployments/celery-deployment.yaml
  - deployments/celerybeat-deployment.yaml
  - deployments/backend-deployment.yaml
  - ingress.yaml
  - service.yaml
#  - persistentvolumeclaims.yaml
images:
  - name: 606544177517.dkr.ecr.us-east-1.amazonaws.com/tinydotcom-backend
    newTag: latest
