# Generated by Django 3.2 on 2022-01-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220125_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='featured_recipe_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_recipe_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
