# Generated by Django 3.2 on 2022-01-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220126_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='featured_recipe_image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured_recipe_image_url',
        ),
    ]
