# Generated by Django 3.2 on 2022-05-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220128_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductvariant',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
