# Generated by Django 3.2 on 2022-05-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220504_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='show_variants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='show_variants',
            field=models.BooleanField(default=False),
        ),
    ]
