# Generated by Django 3.2 on 2022-05-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220504_1113'),
        ('products', '0008_auto_20220504_2216'),
    ]

    operations = [
    ]
