# Generated by Django 3.2 on 2022-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_0007_auto_20220504_1113_0008_auto_20220504_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
