# Generated by Django 3.2 on 2022-06-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('products', '0010_auto_20220513_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fulfillment_center',
            field=models.ManyToManyField(related_name='fulfillment_centers', to='fulfillment.FulfillmentCenter'),
        ),
    ]
