# Generated by Django 3.2 on 2022-06-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_fulfillment_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fulfillment_center',
            new_name='fulfillment_centers',
        ),
    ]
