# Generated by Django 3.2 on 2022-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0003_rename_zipcode_fulfillmentcenter_zipcodes'),
        ('products', '0012_rename_fulfillment_center_product_fulfillment_centers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fulfillment_centers',
            field=models.ManyToManyField(related_name='fulfillment_products', to='fulfillment.FulfillmentCenter'),
        ),
    ]
