# Generated by Django 3.2 on 2022-07-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_fulfillment_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='featured_ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_ingredients',
            field=models.TextField(blank=True),
        ),
    ]
